# web:
#   build: .
#   command: python app.py
#   ports:
#    - "5000:5000"
#   volumes:
#    - .:/code
#   links:
#    - redis
# redis:
#   image: redis

storage:
  hostname: storage-01
  build: docker-storage
  tty: true

db:
  # build: docker-postgres
  hostname: db-01
  image: postgres:9.3
  ports:
    - 5432:5432
  volumes_from:
    - storage
  environment:
    - POSTGRES_DB=testuser
    - POSTGRES_USER=testuser
    - POSTGRES_PASSWORD=testuser

cron:
  hostname: cron-01
  build: docker-cron
  links:
    - db:db
  volumes:
    - ~/backups:/backups
  tty: true
  stdin_open: true

