# web:
#   build: .
#   command: python app.py
#   ports:
#    - "5000:5000"
#   volumes:
#    - .:/code
#   links:
#    - redis
# redis:
#   image: redis

sonarqube:
  image: orangesignal/sonar:4.5.4
  links: 
    - db:database
  ports: 
    - 9000:9000
  environment:
    - SONAR_JDBC_URL=jdbc:postgresql://database:5432/sonar_test
    - SONAR_JDBC_USERNAME=sonar_test
    - SONAR_JDBC_PASSWORD=sonar_test

db:
  # build: docker-postgres
  hostname: db-01
  image: postgres:9.3
  ports:
    - 5432:5432
  volumes_from:
    - storage
  environment:
    - POSTGRES_DB=sonar_test
    - POSTGRES_USER=sonar_test
    - POSTGRES_PASSWORD=sonar_test

storage:
  build: docker-storage
  stdin_open: true

